# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OCTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OCTest

	pod 'Masonry'
	pod 'SDWebImage'
	pod 'AFNetworking'
    pod 'Debugo'

  target 'OCTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
